[versions]
agp = "7.3.1"
kotlin = "1.6.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.3"
espressoCore = "3.4.0"
appcompat = "1.7.0"
kotlinxSerializationJson = "1.7.3"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.3.3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }