[versions]
jackson = "2.21.1"
jna = "5.18.1"
junit = "5.11.4"
lombok = "1.18.42"

[libraries]
jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jackson-datatype-jdk8 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jdk8", version.ref = "jackson" }
jna-platform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jna" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }